services:
  hookstation:
    build: .
    ports:
      - "3548:3000"
    env_file: .env
    container_name: hookstation
    networks:
      - rmtt

networks:
  rmtt:
    driver: bridge
    external: true
